### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by vccolombo** [vccolombo/nossoQL#10]
Precisa ser feita uma documentação para todos os comandos implementados. Opções são criar um arquivo só para a documentação, ou jogar tudo no README. Nesse momento acredito que tanto faz, mas no futuro um arquivo só para a documentação será melhor.

Adicionalmente, precisa ser adicionadas instruções de como instalar o programa (passo a passo para fazer funcionar)

**Comment by JeanGeao** [comment]
https://github.com/vccolombo/nossoQL/wiki
